---
language: python
services: docker

env:
  global:
    - ROLE_NAME: filebeat
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd

      # geerlingguy.java installs too new version on ubuntu1804
      # - MOLECULE_DISTRO: ubuntu1804
      # geerlingguy.logstash fails on ubuntu 16.04
      # - MOLECULE_DISTRO: ubuntu1604
      # geerlingguy.java install too old version on ubuntu 1404
      # - MOLECULE_DISTRO: ubuntu1404

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
