---
- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/{{ filebeat_instance_name }}.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat

- name: Ensure Filebeat SSL key pair directory exists.
  file:
    path: "{{ filebeat_ssl_dir }}"
    state: directory
  when: filebeat_ssl_key_file

- name: Copy Filebeat systemd service definition
  template:
    src: filebeat.service.j2
    dest: "/lib/systemd/system/{{ filebeat_instance_name }}.service"
    owner: root
    group: root
    mode: 0644
  register: filebeat_service
  notify: restart filebeat

- name: Symlink Filebeat systemd service
  file:
    src: "/lib/systemd/system/{{ filebeat_instance_name }}.service"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ filebeat_instance_name }}.service"
    state: link

- name: Register Filebeat systemd service
  systemd:
    name: "{{ filebeat_instance_name }}"
    enabled: true
    state: started
    daemon_reload: true
  when: filebeat_service is changed

- name: Copy SSL key and cert for filebeat.
  copy:
    src: "{{ item }}"
    dest: "{{ filebeat_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ filebeat_ssl_key_file }}"
    - "{{ filebeat_ssl_certificate_file }}"
  notify: restart filebeat
  when: filebeat_ssl_key_file and filebeat_ssl_certificate_file

- name: Enable filebeat modules
  shell: >-
    filebeat modules enable {{ item }}
  args:
    creates: /etc/filebeat/modules.d/{{ item }}.yml
  tags: skip_ansible_lint
  notify: restart filebeat
  with_items: "{{ filebeat_enable_modules }}"

- name: Disable filebeat modules
  shell: >-
    filebeat modules disable {{ item }}
  args:
    creates: /etc/filebeat/modules.d/{{ item }}.yml.disabled
  tags: skip_ansible_lint
  notify: restart filebeat
  with_items: "{{ filebeat_disable_modules }}"
