---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: filebeat_install

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: filebeat_install

- include: config.yml
  when: filebeat_create_config
  tags: filebeat_config

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: "{{ filebeat_instance_name }}"
    state: started
    enabled: true
  tags:
    - filebeat_install
    - filebeat_config
