---
- include: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - not filebeat_rpm_url is defined
  tags: filebeat_install

- name: Install filebeat from rpm url
  yum:
    name: "{{ filebeat_rpm_url }}"
    state: present
    disable_gpg_check: true
    validate_certs: false
  register: filebeat_install
  when:
    - ansible_os_family == 'RedHat'
    - filebeat_rpm_url is defined

- include: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - not filebeat_deb_url is defined
  tags: filebeat_install

- name: Install filebeat from deb url
  apt:
    deb: "{{ filebeat_deb_url }}"
    state: present
  register: filebeat_install
  when:
    - ansible_os_family == 'Debian'
    - filebeat_deb_url is defined

- include: config.yml
  when: filebeat_create_config
  tags: filebeat_config

# WORKAROUND: systemctl restart filebeat_* hangs when filebeat is upgraded
- name: Kill existing filebeat processes
  shell: pgrep filebeat | xargs kill -9  # noqa 306
  failed_when: false
  when: filebeat_force_restart | default( false )

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: "{{ filebeat_instance_name }}"
    state: started
    enabled: true
  tags:
    - filebeat_install
    - filebeat_config
